### ISSUE TITLE
Error in p-value adjustment

### ISSUE THREAD

**Issue by LukasWallrich** [ebbertd/chisq.posthoc.test#1]
Hi there,

I am running post-hoc tests on a 2*6 table. In my mind, that requires 6 post-hoc tests, so that p-values should be increased 6-fold when using the Bonferroni correction. However, they are increased 12-fold. Am I right in thinking that that is a mistake in the function? Or am I getting the logic of the post-hoc test wrong?

Many thanks, all the best,

Lukas

**Comment by ebbertd** [comment]
Hello Lukas,
you might be misunderstanding how this function works. This function does not compute 6 2x2 tables, what it does is to calculate p-values based on the adjusted standardized residuals for the chi-square analysis. So in a 2*6 table the number of comparisons is 12, hence the increase by 12.
Best regards,
Daniel

**Comment by LukasWallrich** [comment]
Thanks for clarifying! Just for my understanding: isn’t that a rather inefficient way to run post-hoc tests? It seems to me that you can get the same information with 6 tests and thus twice the power?
