### ISSUE TITLE
chisq.posthoc.test residuals is different from chisq.test Pearson's residuals 

### ISSUE THREAD

**Issue by xiaofanliang** [ebbertd/chisq.posthoc.test#2]
To my understanding, the residuals chisq.posthoc.test return is Pearson's residuals right? And the document of the package says the x is a matrix passing onto chisq.test function. I used the same dataset to run in both chisq.posthoc.test function and chisq.test function, but the residuals are different. I copy the sample data from [here](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/chisq.test). See the replicable codes below: 

```
M <- as.table(rbind(c(11, 40, 30, 24, 47), c(8, 35, 35, 38, 62)))
dimnames(M) <- list(gender = c("F", "M"),
                    party = c("a","b",'c','d','e'))
chisq.test(M)$residuals
```
![Screen Shot 2020-11-01 at 11 10 53 PM](https://user-images.githubusercontent.com/22874361/97829280-9592d700-1c97-11eb-98fe-62618885a267.png)

```
chisq.posthoc.test(as.table(M))
```
![Screen Shot 2020-11-01 at 11 11 55 PM](https://user-images.githubusercontent.com/22874361/97829306-a80d1080-1c97-11eb-9d6c-bf8b45aae6b9.png)

Please let me know which one is correct and why they do not match. Thanks!

**Comment by ebbertd** [comment]
Nearly right, is is the standardized residuals. Try: `chisq.test(M)$stdres`
